export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT ='USER_LOGOUT';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAIL ='FETCH_PRODUCTS_FAIL';
export const PRODUCT_DESCRIPTION ='PRODUCT_DESCRIPTION';

export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const UPDATE_PRODUCT_INVENTORY ='UPDATE_PRODUCT_INVENTORY';
export const UPDATE_PRODUCT_RATING = 'UPDATE_PRODUCT_RATING';


export const ADD_TO_CART = 'ADD_TO_CART';
export const ALREADY_IN_CART ='ALREADY_IN_CART';
export const DELETE_FROM_CART ='DELETE_FROM_CART';
export const FETCH_FROM_CART = 'FETCH_FROM_CART';

export const OUT_OF_STOCK = 'OUT_OF_STOCK';
export const ON_PURCHASABLE = 'ON_PURCHASABLE';

export const PRODUCT_ITEM_QUANTITY_INCREASE ='PRODUCT_ITEM_QUANTITY_INCREASE';
export const PRODUCT_ITEM_QUANTITY_DECREASE = 'PRODUCT_ITEM_QUANTITY_DEACREASE';

export const CART_ITEM_QUANTITY_INCREASE = 'CART_ITEM_QUANTITY_INCREASE';
export const CART_ITEM_QUANTITY_DECREASE = 'CART_ITEM_QUANTITY_DECREASE';

export const CHECKOUT_ORDER ='CHECKOUT_ORDER';
export const ORDER_PLACED ='ORDER_PLACED';

export const FETCH_ORDERS ='FETCH_ORDERS';

export const ADD_REMOVE_FROM_FILTER = 'ADD_REMOVE_FROM_FILTER';
export const ADD_REMOVE_FROM_PRICE_FILTER =' ADD_REMOVE_FROM_PRICE_FILTER';
export const CLEAR_ALL ='CLEAR_ALL';